### ISSUE TITLE
Feature Request: Clear All

### ISSUE THREAD

**Issue by x4e** [chandler-stimson/vector-draw#4]
Hello,

Thank You for such an amazing tool!

One feature I feel could add benefit is the ability to clear the whole screen, wiping any drawings.
I had two ideas for how this could be integrated into the UI:

* Trash icon is always clickable - when there is a selection it only deletes selection, otherwise it deletes everything. This could be confusing.
* Another icon to wipe the screen.

Let me know what you think, I would also be happy to implement it myself if you could give me some guidance as to the architecture of your codebase (https://matklad.github.io/2021/02/06/ARCHITECTURE.md.html might be helpful).

**Comment by chandler-stimson** [comment]
Hi,

Use Ctrl + A to select all the objects and then delete.

**Comment by x4e** [comment]
Thanks, that is what I was looking for
